# Generated by Django 6.0.7 on 2026-08-20 19:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('M', 'Monitor'), ('P', 'Professor Orientador'), ('A', 'Setor Pedagógico')], max_length=1)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Monitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edital', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=100)),
                ('tipo_bolsa', models.CharField(choices=[('R', 'Remunerada'), ('V', 'Voluntária')], max_length=20)),
                ('valor_bolsa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('agencia', models.CharField(blank=True, max_length=10, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorias_aluno', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorias_orientador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntregaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('arquivo_anexo_ii', models.FileField(help_text='Registro de Frequência Mensal assinado', upload_to='anexos_frequencia/')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado pelo Professor'), ('R', 'Recusado (Necessita Ajuste)')], default='P', max_length=1)),
                ('feedback_professor', models.TextField(blank=True, null=True)),
                ('monitoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.monitoria')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumpriu_plano', models.BooleanField(default=True)),
                ('motivo_nao_cumprimento', models.TextField(blank=True, null=True)),
                ('nota_responsabilidade', models.CharField(max_length=1)),
                ('nota_planejamento', models.CharField(max_length=1)),
                ('nota_relacionamento', models.CharField(max_length=1)),
                ('nota_conhecimento', models.CharField(max_length=1)),
                ('nota_criatividade', models.CharField(max_length=1)),
                ('nota_iniciativa', models.CharField(max_length=1)),
                ('nota_autodesenvolvimento', models.CharField(max_length=1)),
                ('nota_autocritica', models.CharField(max_length=1)),
                ('parecer', models.TextField()),
                ('avaliacao_final', models.CharField(max_length=1)),
                ('recomenda_novamente', models.BooleanField()),
                ('monitoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.monitoria')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_atendidos', models.IntegerField()),
                ('qtd_matriculados', models.IntegerField()),
                ('qtd_aprovados', models.IntegerField()),
                ('qtd_desistentes', models.IntegerField()),
                ('pontos_positivos', models.TextField()),
                ('pontos_negativos', models.TextField()),
                ('sugestoes', models.TextField()),
                ('parecer_colegiado', models.TextField()),
                ('monitoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.monitoria')),
            ],
        ),
        migrations.CreateModel(
            name='AtendimentoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('atividades_desenvolvidas', models.TextField()),
                ('qtd_estudantes_presentes', models.IntegerField(help_text='Monitor declara a quantidade de presentes')),
                ('monitoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.monitoria')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoTrabalhoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('atividades_propostas', models.TextField(help_text='Preenchido pelo Professor')),
                ('atividades_realizadas', models.TextField(help_text='Preenchido pelo Monitor')),
                ('monitoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma.monitoria')),
            ],
        ),
    ]
